### ISSUE TITLE
StratisSoftwareDesign PDF failed to build on Fedora 32

### ISSUE THREAD

**Issue by drckeefe** [stratis-storage/stratis-docs#178] opened 2020-05-12 19:28 UTC
Building docs on Fedora 32 caused a traceback.

Process:
1. git clone https://github.com/stratis-storage/stratis-docs
2. dnf -y install zola lyx
3. cd stratis-docs
4. make
5. traceback

Version of zola and lyx used:
 lyx                                          x86_64         2.3.4.2-1.fc32 
 zola                                         x86_64         0.10.1-1.fc32

Trace:
```
Traceback (most recent call last):
  File "/usr/share/lyx/scripts/convertDefault.py", line 38, in <module>
    output = output.decode()
AttributeError: 'str' object has no attribute 'decode'
Systemcall.cpp (276): Systemcall: 'python -tt "/usr/share/lyx/scripts/convertDefault.py" svg "/tmp/lyx_tmpdir.KBhIpanNlkpK/lyx_tmpbuf0/0_root_stratis-docs_docs_design_stratis-interactions.svg" eps "/tmp/lyx_tmpdir.KBhIpanNlkpK/lyx_tmpbuf0/0_root_stratis-docs_docs_design_stratis-interactions.eps"' finished with exit code 1
Error: Cannot convert file
----------------------------------------
No information for converting svg format files to eps.
Define a converter in the preferences.
Traceback (most recent call last):
  File "/usr/share/lyx/scripts/convertDefault.py", line 38, in <module>
    output = output.decode()
AttributeError: 'str' object has no attribute 'decode'
Systemcall.cpp (276): Systemcall: 'python -tt "/usr/share/lyx/scripts/convertDefault.py" svg "/tmp/lyx_tmpdir.KBhIpanNlkpK/lyx_tmpbuf0/1_root_stratis-docs_docs_design_stratis.svg" eps "/tmp/lyx_tmpdir.KBhIpanNlkpK/lyx_tmpbuf0/1_root_stratis-docs_docs_design_stratis.eps"' finished with exit code 1
Traceback (most recent call last):
  File "/usr/share/lyx/scripts/convertDefault.py", line 38, in <module>
    output = output.decode()
AttributeError: 'str' object has no attribute 'decode'
Systemcall.cpp (276): Systemcall: 'python -tt "/usr/share/lyx/scripts/convertDefault.py" svg "/tmp/lyx_tmpdir.KBhIpanNlkpK/lyx_tmpbuf0/2_root_stratis-docs_docs_design_stratis-bda.svg" eps "/tmp/lyx_tmpdir.KBhIpanNlkpK/lyx_tmpbuf0/2_root_stratis-docs_docs_design_stratis-bda.eps"' finished with exit code 1
```

**Comment by drckeefe** [comment] 2020-05-12 19:31
Building docs on Fedora 30 had no issues.

**Comment by mulkieran** [comment] 2020-05-12 23:45
This is a bug in the ```convertDefault.py``` script on Fedora 32. It's reading the version string of a conversion command and then trying to decode it. We don't execute that line when running on F30 because the default Python for most of us is still Python 2, but on F32 it is Python 3.

We might want to call somebody's attention to it via a BZ; LyX unfortunately uses Trac and SVN.

**Comment by mulkieran** [comment] 2020-05-13 00:24
So, try following the steps in https://bugzilla.redhat.com/show_bug.cgi?id=1827986 and if that doesn't work, there are other things we can try.

**Comment by mulkieran** [comment] 2020-06-15 14:29
lyx 2.3.5 is in stable in Fedora 31, 32, 33 and should fix the bug.

**Comment by mulkieran** [comment] 2020-06-15 15:39
I've confirmed that the doc builds w/out any problems.

**Comment by mulkieran** [comment] 2020-06-15 15:40
Closed, fixed in new release.

**Closed by mulkieran** 2020-06-15 15:40 UTC
